// @ts-check
const savedSettings = localStorage.getItem("private_settings");
const privateSettings = savedSettings ? JSON.parse(savedSettings) : [];
// @ts-ignore
window.gxcfa.chromeG = {
    prefListeners: [],
    app: {
        isInstalled: true,
        InstallState: {
            DISABLED: "disabled",
            INSTALLED: "installed",
            NOT_INSTALLED: "not_installed",
        },
        RunningState: {
            CANNOT_RUN: "cannot_run",
            READY_TO_RUN: "ready_to_run",
            RUNNING: "running",
        },
    },
    contentSettings: {
        unsandboxedPlugins: {},
        popups: {},
        plugins: {},
        notifications: { set() { } },
    },
    contextMenusPrivate: {
        ItemType: {
            CHECKBOX: "CHECKBOX",
            NORMAL: "NORMAL",
            SEPARATOR: "SEPARATOR",
            SUBMENU: "SUBMENU",
            WORKSPACE: "WORKSPACE",
        },
    },
    cookies: {
        get({ name, url }, callback) {
            const cookieString = document.cookie
                .split("; ")
                .find((row) => row.startsWith(name + "="));
            const value = cookieString
                ? decodeURIComponent(cookieString.split("=")[1])
                : null;
            callback(value);
            return value;
        },

        getAll(...args) {
            const cookieArray = document.cookie.split("; ");
            const cookiesObject = {};
            cookieArray.forEach((cookie) => {
                const [key, value] = cookie.split("=");
                cookiesObject[key] = decodeURIComponent(value);
            });
            return cookiesObject;
        },

        getAllCookieStores(...args) {
            return [
                {
                    id: "default",
                    tabIds: [],
                },
            ];
        },

        remove(name) {
            document.cookie = `${name}=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;`;
        },

        set(name, value, options = {}) {
            let cookieString = `${name}=${encodeURIComponent(value)}`;
            if (options.expires) {
                cookieString += `; expires=${options.expires.toUTCString()}`;
            }
            if (options.path) {
                cookieString += `; path=${options.path}`;
            }
            if (options.domain) {
                cookieString += `; domain=${options.domain}`;
            }
            if (options.secure) {
                cookieString += `; secure`;
            }
            if (options.sameSite) {
                cookieString += `; samesite=${options.sameSite}`;
            }
            document.cookie = cookieString;
        },

        onChanged: {},
        OnChangedCause: {
            EVICTED: "evicted",
            EXPIRED: "expired",
            EXPIRED_OVERWRITE: "expired_overwrite",
            EXPLICIT: "explicit",
            OVERWRITE: "overwrite",
        },
        SameSiteStatus: {
            LAX: "lax",
            NO_RESTRICTION: "no_restriction",
            STRICT: "strict",
            UNSPECIFIED: "unspecified",
        },
    },
    dom: {},
    easySetupPrivate: {},
    management: {
        get() { },
        setEnabled() { },
        getAll() { },
        onDisabled: {
            addListener() { },
            removeListener() { },
        },
        onEnabled: {
            addListener() { },
            removeListener() { },
        },
        onUninstalled: {
            addListener() { },
            removeListener() { },
        },
        onInstalled: {
            addListener() { },
            removeListener() { },
        },
        ExtensionDisabledReason: {
            PERMISSIONS_INCREASE: "permissions_increase",
            UNKNOWN: "unknown",
        },
        ExtensionInstallType: {
            ADMIN: "admin",
            DEVELOPMENT: "development",
            NORMAL: "normal",
            OTHER: "other",
            SIDELOAD: "sideload",
        },
        ExtensionType: {
            EXTENSION: "extension",
            HOSTED_APP: "hosted_app",
            LEGACY_PACKAGED_APP: "legacy_packaged_app",
            LOGIN_SCREEN_EXTENSION: "login_screen_extension",
            PACKAGED_APP: "packaged_app",
            THEME: "theme",
        },
        LaunchType: {
            OPEN_AS_PINNED_TAB: "OPEN_AS_PINNED_TAB",
            OPEN_AS_REGULAR_TAB: "OPEN_AS_REGULAR_TAB",
            OPEN_AS_WINDOW: "OPEN_AS_WINDOW",
            OPEN_FULL_SCREEN: "OPEN_FULL_SCREEN",
        },
    },
    operaResourcesPrivate: {
        Component: {
            BABE: "babe",
            BOOKMARKS: "bookmarks",
            BOOKMARKS_PANEL: "bookmarks_panel",
            BOOSTER_SIDEBAR: "booster_sidebar",
            CRYPTO_EXTENSIONS_LIST: "crypto_extensions_list",
            CRYPTOWALLET: "cryptowallet",
            DIALOG: "dialog",
            DOWNLOADS: "downloads",
            EXTENSIONS: "extensions",
            FEEDBACK_POPUP: "feedback_popup",
            GENERIC: "generic",
            HISTORY: "history",
            HISTORY_PANEL: "history_panel",
            LIMITERS_SIDEBAR: "limiters_sidebar",
            NAVBAR: "navbar",
            PERSONALNEWS: "personalnews",
            PLAYER_SERVICE: "player_service",
            PRIVATE_MODE: "private_mode",
            SIDEBAR_SETUP: "sidebar_setup",
            STARTPAGE: "startpage",
            STYLEGUIDE: "styleguide",
            TABS: "tabs",
            VIDEO_CONFERENCE_DETACHED: "video_conference_detached",
            VIDEOPOPOUT: "videopopout",
            VPN_PRO: "vpn_pro",
            WEB3_SELECTOR: "web3_selector",
        },
        getStrings(a, b) {
            return b({
                "addSuggestionToSpeedDial": "Add to Speed Dial",
                "addToOpera": "Add to Opera",
                "addToSpeedDial": "Add to Opera",
                "addToSpeedDialAddButton": "Add it",
                "addToSpeedDialSuggestionHeadline": "Suggestions",
                "add_to_bookmarks": "Add to bookmarks",
                "addressBarDropdownCities": false,
                "addressSearchSuggestionPlaceholder": "Type address to add to your Speed Dial",
                "addressbarYandexBox": false,
                "aiToolsAiPromptsTextHighlight": "AI Prompts in text highlight popup",
                "aiToolsDescription": "Enables AI prompts in the address bar and text highlight popup, connected to services such as ChatGPT and ChatSonic in Opera Browser’s sidebar.",
                "aiToolsDisclaimer": "AI Services should not be employed for any legal, medical, or advisory purposes. We advise you to apply caution and check facts.",
                "aiToolsInSidebar": "AI Services in sidebar",
                "aiToolsLabel": "AI Services",
                "aiToolsSidebarSetup": "Sidebar Settings",
                "aliexpressSearchPlaceholder": "Search for products",
                "animationsBlink": "Blink",
                "animationsCustom": "Custom",
                "animationsHovercraft": "Hovercraft",
                "animationsNone": "None",
                "animationsSectionTitle": "Animations",
                "animationsSlideOut": "Slide out",
                "animationsTileAnimation": "Tile animation",
                "animationsTileClickAnimation": "Tile click animation",
                "animationsTileHoverAnimation": "Tile hover animation",
                "animationsTileShaderBasedAnimations": "Use shader-based animations",
                "animationsWhizz": "Basic",
                "appearanceAutoTabIslandLabel": "Automatically create tab islands",
                "appearanceBiggerTilesLabel": "Use bigger tiles",
                "appearanceBookmarksLabel": "Show bookmarks bar",
                "appearanceCashbackWidgetLabel": "Show Cashback widget",
                "appearanceForceDarkMode": "Force dark mode on pages",
                "appearanceForceDarkModeTooltip": "Enable dark theme on any page when Opera is in dark mode.\n        This feature is experimental and may not work correctly on all websites.",
                "appearanceNewsLabel": "Show News",
                "appearanceRecommendedStoriesLabel": "Show Content Picks",
                "appearanceSectionTitle": "Appearance",
                "appearanceSidebarAutohide": "Autohide",
                "appearanceSidebarAutohideLabel": "Automatically hide sidebar",
                "appearanceSidebarDisabled": "Off",
                "appearanceSidebarEnabled": "On",
                "appearanceSidebarLabel": "Show sidebar",
                "appearanceSuggestionLabel": "Show Speed Dial suggestions",
                "appearanceWeatherLabel": "Show Weather",
                "blockedContentStats": false,
                "bookingModalDirectLinkLabel": "Go to Booking.com",
                "bookingModalDontShowAgainLabel": "Don't show this again",
                "bookmark_image_height": 168,
                "bookmark_image_width": 264,
                "bookmarks_export_context_menu": "Export bookmarks",
                "bookmarks_import_context_menu": "Import bookmarks",
                "campaignsMenuCancel": "Cancel",
                "campaignsMenuDontShowAgain": "Don't show again",
                "campaignsMenuRemindTomorrow": "Remind me tomorrow",
                "cancel_button": "Cancel",
                "cashback": false,
                "cashbackWarningLink": "Switch to browsing mode",
                "cashbackWarningMsg": "You’re browsing in a Smart Shopping mode.",
                "cashbackWidgetEnabled": false,
                "channel-name": "Stable",
                "chromaSupport": "GX Lights",
                "clearBrowsingDataButton": "Clear browsing data…",
                "clearBrowsingDataLearnMore": "Learn more",
                "clearBrowsingDataSectionTitle": "Clear browsing data",
                "closeLabel": "Close",
                "colorPickerLess": "Basic",
                "colorPickerMore": "Extended",
                "colorSectionTitle": "Color",
                "colorThemeEnabled": false,
                "configurationLinkTitle": "Configuration",
                "contentFilteringEnabled": true,
                "content_context_copylinklocation": "Copy link addr&ess",
                "context_menu_copy": "Copy",
                "context_menu_cut": "Cut",
                "context_menu_delete": "Remove",
                "context_menu_delete_device_folder": "Remove device folder",
                "context_menu_delete_selected": "Remove selected",
                "context_menu_edit": "Edit…",
                "context_menu_empty_trash": "Empty trash",
                "context_menu_move_to_trash": "Move to Trash",
                "context_menu_move_to_trash_selected": "Move selected to Trash",
                "context_menu_new_folder": "New folder",
                "context_menu_new_folder_with_selection": "New folder with selection",
                "context_menu_open_folder_in_new_tab": "Open all in new tabs",
                "context_menu_open_folder_in_new_window": "Open all in new window",
                "context_menu_open_folder_in_private_window": "Open all in new private window",
                "context_menu_open_folder_in_workspace": "Open all in &workspace",
                "context_menu_open_in_new_tab": "Open in new tab",
                "context_menu_open_in_new_window": "Open in new window",
                "context_menu_open_in_private_window": "Open in new private window",
                "context_menu_open_in_workspace": "Open in &workspace",
                "context_menu_open_selected_in_new_tab": "Open selected in new tabs",
                "context_menu_open_selected_in_new_window": "Open selected in new window",
                "context_menu_open_selected_in_private_window": "Open selected in new private window",
                "context_menu_paste": "Paste",
                "context_menu_select_all": "Select all",
                "context_menu_sort_alphabetically": "Sort alphabetically",
                "context_menu_undo_delete_selected": "Restore",
                "contextmenuAddSpeedDial": "Add to Speed Dial",
                "contextmenuChangeTheme": "Change wallpaper",
                "contextmenuDelete": "Remove",
                "contextmenuDontShowAgain": "Don't show again",
                "contextmenuEdit": "Edit",
                "contextmenuEditTitle": "Edit title",
                "contextmenuMoveToTrash": "Move to Trash",
                "contextmenuOpenAllSpeeddials": "Open all",
                "contextmenuReloadThumbnail": "Reload",
                "continueOnAmazonItem": "1 item",
                "continueOnAmazonItems": "$1 items",
                "continueOnAmazonSectionName": "Continue shopping",
                "continueOnAnyDontShowAgain": "Don't show again",
                "continueOnAnyNotNowMenuCancel": "Cancel",
                "continueOnAnyRemindMeTomorrow": "Remind me tomorrow",
                "continueOnBooking": true,
                "continueOnBookingDontShowIveBooked": "Don’t show again, I’ve already booked",
                "continueOnBookingDontShowNotInterested": "Don’t show again, I’m not interested",
                "continueOnBookingRemindMeLater": "Remind me later",
                "continueOnBookingRemoveAllItems": "Clear all Booking.com items",
                "continueOnBookingSectionName": "Continue on Booking.com",
                "continueShopping": true,
                "continueShoppingDiscardAllItems": "Discard all items",
                "continueShoppingExplore": false,
                "continueShoppingFeedbackHint": "Send your opinion",
                "continueShoppingFeedbackRatingAverage": "Could be better",
                "continueShoppingFeedbackRatingBad": "Not at all",
                "continueShoppingFeedbackRatingGood": "It's cool",
                "continueShoppingHelpHint": "How does it work?",
                "continueShoppingNewItem": "1 new item",
                "continueShoppingNewItems": "$1 new items",
                "defaultBrowserMakeDefaultButton": "Make Opera GX default browser",
                "defaultBrowserNotDefaultCaption": "Opera GX is not currently your default browser.",
                "defaultBrowserPromptButtonLater": "Ask me later",
                "defaultBrowserPromptButtonNo": "No",
                "defaultBrowserPromptButtonYes": "Yes",
                "defaultBrowserPromptCaption": "Would you like to make $1 your everyday browser?",
                "defaultBrowserPromptDontAskAgain": "Don't ask again",
                "defaultBrowserSectionTitle": "Default browser",
                "defaultFolderName": "Folder",
                "delete": "Delete",
                "delete_device_folder_confirmation": "Removing a device folder will remove all the Speed Dial entries on that device.\n\nDo you really want to remove this device folder?",
                "delete_tooltip": "Remove",
                "done": "Done",
                "dontShowAgain": "Do not show again",
                "dontShowSuggestionAgain": "Don't show again",
                "downloadsLocationChangeButton": "Change…",
                "downloadsLocationLabel": "Download location:",
                "earlyBirdEnableInSettingsButtonCaption": "Enable in Settings",
                "earlyBirdLabel": "Early Bird",
                "easySetupFullStats": false,
                "easySetupHintDismiss": "Got it",
                "easySetupHintLead": "Now always on hand",
                "easySetupHintText": "Quickly adjust your browser’s theme, wallpaper, Speed Dial tile size, turn on ad blocker and more…",
                "easySetupHintTitle": "Easy Setup",
                "easySetupTitle": "Easy setup",
                "easyShareAppUrl": "https://flow.opera.com/ext/v1/start-gx",
                "edit": "Edit",
                "editAddressLabel": "Address",
                "editNameLabel": "Name",
                "edit_bookmark": "Edit bookmark",
                "edit_tooltip": "Edit",
                "empty_folder_add_first_bookmark": "Add your first bookmark using",
                "empty_folder_import_button": "Import bookmarks",
                "empty_folder_import_text": "Or import your favorite websites from another browser",
                "empty_search_headline": "No luck finding \"$1\"",
                "empty_trash_button": "Empty trash",
                "empty_trash_confirmation": "Do you really want to empty Trash and permanently remove its contents?",
                "enableForceDarkFromSettingsFeatureEnabled": false,
                "extensionInstallError": "Extension installation failed.",
                "extensionManageSettings": "Manage extensions…",
                "extensionSettingsDelete": "Remove",
                "extensionSettingsDisable": "Disable",
                "extensionSettingsFeaturedFeedURL": "https://addons.opera.com/extensions/api/featured/1.0/plus-dialog/",
                "extensionSettingsOptions": "Options",
                "extensionWebstoreDetailURLPrefix": "https://addons.opera.com/extensions/details/app_id/",
                "featureFeedbackCancelButton": "Not now",
                "featureFeedbackCommentsPlaceholder": "Tell us more (your opinion matters)",
                "featureFeedbackHeader": "How useful is this feature?",
                "featureFeedbackSubmitButton": "Send",
                "featureFeedbackTitle": "Your opinion",
                "featuresBackgroundMusicLabel": "Background music",
                "featuresBlockAdsLabel": "Block ads",
                "featuresBlockTrackersLabel": "Block trackers",
                "featuresDailyWallpapersFeedback": "Feedback",
                "featuresEasyShareLabel": "My Flow",
                "featuresForceDarkMode": "Force dark pages",
                "featuresForceDarkModeFeedback": "beta",
                "featuresKeyboardSoundsLabel": "Keyboard sounds",
                "featuresMonadyInSidebar": "GX Corner in sidebar",
                "featuresPlaySoundsLabel": "Browser sounds",
                "featuresPlayThemeSoundsLabel": "Theme sounds",
                "featuresSaveBatteryLabel": "Save battery",
                "featuresSectionTitle": "Features",
                "featuresShowSplashLabel": "Splash screen on startup",
                "feedbackBadge": "Feedback",
                "folderFilterPlaceholder": "Search",
                "folder_names": {
                    "_imported_from_opera_link_": "Imported From Opera Link",
                    "_reading_list_": "Reading list",
                    "_shopping_": "Shopping",
                    "_travel_": "Travel",
                    "_videos_": "Videos"
                },
                "fontfamily": "'Segoe UI', Tahoma, sans-serif",
                "fontfamilyMd": "'Segoe UI', Tahoma, sans-serif",
                "fontsize": "75%",
                "goToBrowserSettings": "Go to full browser settings",
                "goToSpeedDial": "Go to Speed Dial",
                "gxCalendarPreviewEnabled": true,
                "gxChromaSettingsDuplicateSet": "Duplicate",
                "gxChromaSettingsDuplicatedSetName": "Duplicate of $1",
                "gxChromaSettingsExport": "Export",
                "gxCornerCMSEnabled": true,
                "gxDailyWallpapersFeatureEnabled": false,
                "gxGameStripsAddLabel": "Add Game Strip",
                "gxGameStripsEnabled": true,
                "gxGameStripsLabel": "Game strips",
                "gxPanicButton": true,
                "gxPostMortemCleanup": true,
                "gxShadersExceptions": false,
                "gxUi2024": true,
                "gxWidgetsAutohidePanel": "Always hide panel",
                "gxWidgetsGamesLabel": "Show GX Games",
                "gxWidgetsGxMeEditLabel": "Edit profile",
                "gxWidgetsGxMeLabel": "Show GX.me",
                "gxWidgetsHackerViewLabel": "Show Hacker view",
                "gxWidgetsLinksLabel": "Show Links",
                "gxWidgetsLogoutLabel": "Log out",
                "gxWidgetsModsLabel": "Show GX Mods",
                "gxWidgetsSectionTitle": "Widgets",
                "gxWidgetsSignUpLabel": "Sign up",
                "hasSyncedSpeedDials": false,
                "header": "Bookmarks",
                "importSettingsButton": "Import bookmarks and settings…",
                "importSettingsCaption": "Copy passwords, history, cookies and favorite pages from another browser.",
                "importSettingsSectionTitle": "Import passwords and bookmarks",
                "import_export_bookmarks_text": "Import/Export…",
                "isGX": true,
                "isGX2024": true,
                "isPrivateWindow": false,
                "labelCancel": "Cancel",
                "labelOk": "OK",
                "language": "en",
                "layoutSectionTitle": "Layout",
                "learnMore": "Learn more",
                "learnMoreURL": "https://help.opera.com/latest/security-and-privacy/#privateWindow",
                "liveBackground": true,
                "liveWallpaperConfigureButton": "Configure live wallpaper",
                "liveWallpaperSetWindowsButton": "Set as Windows wallpaper",
                "local_speed_dial_folder_name": "Speed Dial",
                "locationCountry": "TR",
                "lucidModeSectionTitle": "RGX",
                "mainDescription": "As soon as you close all private windows, all the information connected with them will be erased.",
                "mondayApiDomain": "https://gx.opera-api2.com",
                "mondayNewsHeader": "Daily news",
                "mondaySettingsModalTitle": "GX Corner",
                "mondaySettingsPlatformsHeader": "Platforms",
                "mondaySettingsSectionsHeader": "Sections",
                "move_to_trash_tooltip": "Move to Trash",
                "navRateOpera": "Rate Opera",
                "netflixSuggestionsNewLabel": "New",
                "netflixSuggestionsPoweredByLabel": "Powered by",
                "netflixSuggestionsScrollHandleCaption": "New Netflix shows for you. Watch now",
                "netflixSuggestionsSeasonsPluralLabel": "seasons",
                "netflixSuggestionsSeasonsSingularLabel": "season",
                "netflixSuggestionsWatchTrailerButton": "watch trailer",
                "networkError": "Unknown network error.",
                "newMdExtensionsFlagSet": true,
                "newStickySiteFeaturesEnabled": false,
                "new_folder_main_view_button_tooltip": "Add a new folder to the current folder",
                "new_folder_menu_button": "Add",
                "new_folder_placeholder": "New folder",
                "newsCDN": "",
                "newsOnStartpageHeaderCategoryAll": "All",
                "newsOnStartpageHeaderChooseLanguageAndCountry": "Choose language and country",
                "newsOnStartpageHeaderSuggestedForYou": "Suggested for you",
                "newsOnStartpageSectionTitle": "The news for you",
                "not_bookmarked": "(Not bookmarked)",
                "ok_button": "OK",
                "open_items_button": "Open items",
                "open_many_confirmation": "Do you really want to open $1 items?",
                "os": {
                    "PLATFORM_LINUX": "lin",
                    "PLATFORM_MAC": "mac",
                    "PLATFORM_WIN": "win",
                    "VERSION_10": 7,
                    "VERSION_7": 4,
                    "VERSION_8": 5,
                    "VERSION_XP": 1,
                    "platform": "win",
                    "version": 20
                },
                "other_speed_dials_folder_name": "Other Speed Dials",
                "pageTabTitle": "$1 - $2",
                "pinboard": true,
                "placeholderEnterSiteAddress": "Type address to add to your Speed Dial",
                "placeholderFilter": "Filter",
                "placeholderSearch": "Search",
                "playAgain": true,
                "playAgainSectionName": "Play again on GX.games",
                "plusButtonTitle": "Add a site",
                "plusButtonTitleShort": "Add site",
                "privacyAndSecurityBrowsingDataClearButton": "Clear",
                "privacyAndSecurityBrowsingDataLabel": "Browsing data",
                "privacyAndSecurityEnableInSettingsButtonCaption": "Enable in Settings",
                "privacyAndSecuritySectionTitle": "Privacy & Security",
                "privacyAndSecurityVPNLabel": "VPN",
                "privacyProtectionEnabled": true,
                "privacy_warning_in_bookmarks_popup": "This bookmark will remain saved when you leave private mode",
                "privateModeTitle": "Private browsing",
                "productName": "Opera GX",
                "promoBadgeLabel": "New",
                "promoButtonLabel": "Try it",
                "promoWorkspacesDescription": "Use other Workspaces",
                "promoWorkspacesHeader": "Too many opened tabs?",
                "rateOpera": "Rate Opera",
                "rateOperaCommentPlaceholder": "Comments",
                "rateOperaDialogAriaLabel": "Rate Opera dialog",
                "rateOperaEmailPlaceholder": "Email address",
                "rateOperaLabelAverage": "Average",
                "rateOperaLabelBad": "Bad",
                "rateOperaLabelClickToRate": "Click to rate",
                "rateOperaLabelExcellent": "Excellent",
                "rateOperaLabelGood": "Good",
                "rateOperaLabelTerrible": "Terrible",
                "rateOperaNoThanksButton": "No thanks",
                "rateOperaSubmitButton": "Submit",
                "reactinatorClose": "Close",
                "reactinatorMute": "Mute",
                "reactinatorNext": "Next track",
                "reactinatorPrev": "Previous track",
                "reactinatorRemove": "Remove",
                "reactinatorResize": "Resize",
                "reactinatorUnmute": "Unmute",
                "reactinatorUpload": "Import",
                "recentWallpaperTitle": "Recent wallpaper",
                "recordSessionEventStatsForTesting": false,
                "reloadPage": "Reload",
                "removeWallpaperTitle": "Remove wallpaper",
                "remove_device_folder_button": "Remove device folder",
                "rgx3AdvancedPrefs": true,
                "richWallpapers": true,
                "runAtStartupEnabled": true,
                "searchButton": "Search",
                "searchButtonLabel": "Search",
                "searchEngineSwitchLabel": "Switch to Google",
                "searchEngineSwitchSuggestion": "Would you like to change the search engine to Google?",
                "searchPageHelpText": "Maybe try using a different search query?",
                "searchPageNoMatches": "Nothing found for \"$1\"",
                "searchPageTitle": "Search results",
                "searchTheWeb": "Search the web",
                "search_placeholder": "Search bookmarks",
                "search_title": "Search results for \"$1\"",
                "select_tooltip": "Select",
                "selectedWallpaperTile": "Selected wallpaper",
                "sharpenCompareModeButton": "Split preview",
                "sharpenImagesLabel": "Enhance images",
                "sharpenNvidiaVSRSupportedLabel": "RGX overrides RTX Video Super Resolution",
                "sharpenVideosLabel": "Enhance videos",
                "shoppingCorner": false,
                "showNextWallpapersTitle": "Show next wallpapers",
                "showPreviousWallpapersTitle": "Show previous wallpapers",
                "show_bookmarks_bar": "Show the bookmarks bar",
                "sideProfilesEasySetupButtonCaption": "Manage",
                "sideProfilesEasySetupLabel": "Profiles",
                "sideProfilesEnabled": true,
                "sideProfilesManageButton": "Manage Profiles",
                "sideProfilesSectionDescription": "Create separate versions of Opera GX, each with its own bookmarks, history, passwords, cookies, and settings.",
                "sideProfilesSectionTitle": "Profiles",
                "singlesDayTitle": "Today is AliExpress Singles' Day!",
                "singlesDayTitleCounterPrefix": "AliExpress Singles' Day in:",
                "speedDialURL": "chrome://startpage/",
                "startPageContentEnabled": false,
                "startPageSectionTitle": "Start Page",
                "startPageSyncBanner": false,
                "suggestionsHeader": "Suggestions",
                "switchGoBackToNew": "Go back to the new start page",
                "switchGoBackToOld": "Go back to the old start page",
                "switchGoToNew": "Try out the new start page",
                "switchGoToNewDismissTooltip": "Not now",
                "switchGoToNewTooltip": "Switch to the new start page",
                "switchSearchEngineToYandex": "Switch default search engine and search Yandex from address bar",
                "switchSearchEngineToYandexButton": "Switch to Yandex",
                "syncBannerButton": "Turn on synchronization",
                "syncBannerDesc": "Sync your bookmarks, tabs, passwords to back them up and access on connected devices",
                "syncBannerTitle": "Back up your Opera browser",
                "systemThemeFeatureEnabled": true,
                "textdirection": "ltr",
                "themeEnv": "",
                "themesAdvancedPreviewHex": "Preview and HEX Value",
                "themesAdvancedPrimary": "Primary Color",
                "themesAdvancedPrimaryLight": "Primary Light Color",
                "themesAdvancedSecondary": "Secondary Color",
                "themesAdvancedSecondaryLight": "Secondary Light Color",
                "themesAdvancedSection": "Custom Theme",
                "themesAdvancedTitle": "Advanced Configuration",
                "themesBackLink": "Back",
                "themesDarkThemeLabel": "Dark",
                "themesLightThemeLabel": "Light",
                "themesLink": "Configuration",
                "themesSectionTitle": "Theme",
                "themesSystemThemeLabel": "Auto",
                "title": "Speed Dial",
                "transparentProductPages": true,
                "trash_bookmark_tooltip": "Move to Trash",
                "undo_delete_button": "Undo delete",
                "view_in_bookmarks": "View in bookmarks",
                "view_mode_toggle_tooltip": "Toggle view mode",
                "vpnDescription": "If you want even more privacy - turn on the VPN.",
                "vpnPro": true,
                "wallpaperTakeover": true,
                "wallpaperTitle": "Wallpaper",
                "wallpapersAddNew": "Add your wallpaper",
                "wallpapersAllLabel": "All wallpapers",
                "wallpapersDesktopLabel": "Desktop",
                "wallpapersGetMore": "Get more wallpapers",
                "wallpapersGetMoreLink": "Get more wallpapers",
                "wallpapersRecentLabel": "Recent wallpapers",
                "wallpapersSectionTitle": "Wallpapers",
                "wallpapersSettingCustom": "Custom",
                "wallpapersSettingDaily": "Daily",
                "wallpapersSettingDailyDescription": "This feature rotates your wallpaper every day.",
                "wallpapersSettingTheme": "Theme",
                "wallpapersShowWallpaperLabel": "Show wallpaper",
                "wallpapersSiteURL": "https://addons.opera.com/wallpapers/?gx&ref=page",
                "wallpapersUseCustomWallpaperLabel": "Use custom wallpaper",
                "weatherCheckForecast": "Check forecast",
                "weatherContextMenuChangeLocation": "Change location",
                "weatherContextMenuDetectLocation": "Detect current location",
                "weatherCustomLocationCancel": "Cancel",
                "weatherCustomLocationSave": "Save",
                "weatherForecastNotAvailable": "Weather forecast not available.",
                "weatherModalAgree": "Agree",
                "weatherModalCancel": "Cancel",
                "weatherModalChangeYourLocation": "Change your location",
                "weatherModalGeolocationServicesExplanation": "To get a correct weather forecast, the browser will send a request to Google Location Services to determine your location and forward it to Opera.",
                "weatherModalPrivacyInfo": "Opera servers do not store or share your location with any third party, including the provider of the weather forecast.",
                "weatherModalPrivacyPolicy": "Privacy policy",
                "weatherModalSetLocationManually": "Set location manually",
                "weatherModalTitle": "Weather Location",
                "weatherSetupYourCity": "Set up your city",
                "webSearchSuggestionsLabel": "Popular searches",
                "webstoreLaunchURLForContextMenu": "https://addons.opera.com/extensions/?tag=speeddial&order=popular",
                "webuiDebugModeEnabled": false,
                "zenNewsLeadsMenuCancel": "Cancel",
                "zenNewsLeadsMenuDontShowAgain": "Don't show again",
                "zenNewsLeadsMenuRemindLater": "Remind me later",
                "zenNewsLeadsScrollToNews": "Scroll to news",
                "zenNewsLeadsTitle": "Yandex Zen",
                "zenNewsLoadErrorSimulate": false,
                "zenNewsOnStartpageScrollHandleCaption": "Yandex Zen news for you is below. See now."
            });
        },
    },
    runtime: {
        id: "ocpleophfhddnogoadhmhpbjanddmnnj",
        onConnect: {},
        ContextType: {
            BACKGROUND: "BACKGROUND",
            OFFSCREEN_DOCUMENT: "OFFSCREEN_DOCUMENT",
            POPUP: "POPUP",
            SIDE_PANEL: "SIDE_PANEL",
            TAB: "TAB",
        },
        OnInstalledReason: {
            CHROME_UPDATE: "chrome_update",
            INSTALL: "install",
            SHARED_MODULE_UPDATE: "shared_module_update",
            UPDATE: "update",
        },
        OnRestartRequiredReason: {
            APP_UPDATE: "app_update",
            OS_UPDATE: "os_update",
            PERIODIC: "periodic",
        },
        PlatformArch: {
            ARM: "arm",
            ARM64: "arm64",
            MIPS: "mips",
            MIPS64: "mips64",
            X86_32: "x86-32",
            X86_64: "x86-64",
        },
        PlatformNaclArch: {
            ARM: "arm",
            MIPS: "mips",
            MIPS64: "mips64",
            X86_32: "x86-32",
            X86_64: "x86-64",
        },
        PlatformOs: {
            ANDROID: "android",
            CROS: "cros",
            FUCHSIA: "fuchsia",
            LINUX: "linux",
            MAC: "mac",
            OPENBSD: "openbsd",
            WIN: "win",
        },
        RequestUpdateCheckStatus: {
            NO_UPDATE: "no_update",
            THROTTLED: "throttled",
            UPDATE_AVAILABLE: "update_available",
        },
    },
    settingsPrivate: {
        getAllPrefs(callback) {
            callback(privateSettings);
            return privateSettings;
        },
        getPref(key, callback) {
            const value = privateSettings.find((setting) => setting.key === key);
            if (callback) callback(value);
            return value;
        },
        setPref(key, value, callback) {
            const index = privateSettings.findIndex(
                (setting) => setting.key === key
            );
            const newValue = {
                key,
                value,
                userControlDisabled: false,
                type: (typeof value).toUpperCase(),
            };
            if (index === -1) {
                privateSettings.push(newValue);
            } else {
                privateSettings[index] = newValue;
            }
            window.chrome.prefListeners.forEach((f) => f([newValue]));
            localStorage.setItem(
                "private_settings",
                JSON.stringify(privateSettings)
            );
            if (callback) callback([true]);
        },
        dispatchChange() {
            window.chrome.prefListeners.forEach((f) => f(privateSettings));
        },
        onPrefsChanged: {
            addListener(f) {
                window.chrome.prefListeners.push(f);
            },
            removeListener(f) {
                window.chrome.prefListeners = window.chrome.prefListeners.filter((e) => e !== f);
            },
        },
        ControlledBy: {
            CHILD_RESTRICTION: "CHILD_RESTRICTION",
            DEVICE_POLICY: "DEVICE_POLICY",
            EXTENSION: "EXTENSION",
            OWNER: "OWNER",
            PARENT: "PARENT",
            PRIMARY_USER: "PRIMARY_USER",
            USER_POLICY: "USER_POLICY",
        },
        Enforcement: {
            ENFORCED: "ENFORCED",
            PARENT_SUPERVISED: "PARENT_SUPERVISED",
            RECOMMENDED: "RECOMMENDED",
        },
        PrefType: {
            BOOLEAN: "BOOLEAN",
            DICTIONARY: "DICTIONARY",
            LIST: "LIST",
            NUMBER: "NUMBER",
            STRING: "STRING",
            URL: "URL",
        },
    },
    tabs: {
        async getCurrent(cb) {
            const val = location.href;
            cb(val);
            return val;
        },
        async update(data) {
            if (data && data.url) {
                location.href = data.url;
            }
        },
        async create(data) {
            if (data && data.url) {
                // @ts-ignore
                window.open(data.url, "_blank").focus();
            }
        },
        async query(info, cb) {
            const val = [];
            cb(val);
            return val;
        },
        onZoomChange: {},
        onReplaced: {},
        onRemoved: {},
        onAttached: {},
        onDetached: {},
        onHighlighted: {},
        onActivated: {},
        onMoved: {},
        onUpdated: {},
        onCreated: {},
        CSSOrigin: {
            AUTHOR: "author",
            USER: "user",
        },
        ImageFormat: {
            JPEG: "jpeg",
            PNG: "png",
        },
        MutedInfoReason: {
            CAPTURE: "capture",
            EXTENSION: "extension",
            USER: "user",
        },
        RunAt: {
            DOCUMENT_END: "document_end",
            DOCUMENT_IDLE: "document_idle",
            DOCUMENT_START: "document_start",
        },
        TabStatus: {
            COMPLETE: "complete",
            LOADING: "loading",
            UNLOADED: "unloaded",
        },
        WindowType: {
            APP: "app",
            DEVTOOLS: "devtools",
            NORMAL: "normal",
            PANEL: "panel",
            POPUP: "popup",
        },
        ZoomSettingsMode: {
            AUTOMATIC: "automatic",
            DISABLED: "disabled",
            MANUAL: "manual",
        },
        ZoomSettingsScope: {
            PER_ORIGIN: "per-origin",
            PER_TAB: "per-tab",
        },
        MAX_CAPTURE_VISIBLE_TAB_CALLS_PER_SECOND: 2,
        TAB_ID_NONE: -1,
        TAB_INDEX_NONE: -1,
    },
    webNavigation: {
        onHistoryStateUpdated: {},
        onTabReplaced: {},
        onReferenceFragmentUpdated: {},
        onCreatedNavigationTarget: {},
        onErrorOccurred: {},
        onCompleted: {},
        onDOMContentLoaded: {},
        onCommitted: {},
        onBeforeNavigate: {},
        TransitionQualifier: {
            CLIENT_REDIRECT: "client_redirect",
            FORWARD_BACK: "forward_back",
            FROM_ADDRESS_BAR: "from_address_bar",
            SERVER_REDIRECT: "server_redirect",
        },
        TransitionType: {
            AUTO_BOOKMARK: "auto_bookmark",
            AUTO_SUBFRAME: "auto_subframe",
            FORM_SUBMIT: "form_submit",
            GENERATED: "generated",
            KEYWORD: "keyword",
            KEYWORD_GENERATED: "keyword_generated",
            LINK: "link",
            MANUAL_SUBFRAME: "manual_subframe",
            RELOAD: "reload",
            START_PAGE: "start_page",
            TYPED: "typed",
        },
    },
    windows: {
        create() { },
        onBoundsChanged: {},
        onFocusChanged: {},
        onRemoved: {},
        onCreated: {},
        CreateType: {
            NORMAL: "normal",
            PANEL: "panel",
            POPUP: "popup",
        },
        WindowState: {
            FULLSCREEN: "fullscreen",
            LOCKED_FULLSCREEN: "locked-fullscreen",
            MAXIMIZED: "maximized",
            MINIMIZED: "minimized",
            NORMAL: "normal",
            PARENT: "parent",
        },
        WindowType: {
            APP: "app",
            DEVTOOLS: "devtools",
            NORMAL: "normal",
            PANEL: "panel",
            POPUP: "popup",
        },
        WINDOW_ID_CURRENT: -2,
        WINDOW_ID_NONE: -1,
    },
};