permissions: read-all

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    uses: ./.github/workflows/node.js.yml
  publish:
    permissions: write-all
    needs: build-and-test
    uses: ./.github/workflows/publish.yml
