# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
#
name: "Node build, release & publish"

on:
  workflow_call

env:
  NODE_AUTH_TOKEN: ${{secrets.npm_token}}

jobs:
  publish-npm:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          always-auth: true
      - run: pnpm i
      - run: pnpm run --if-present build
      - run: pnpm npm-pack-zip
      - name: Get version
        id: get-version
        run: |
          VERSION=$(jq -r '.version' package.json)
          TITLE="Release v$VERSION"  # Customize title format if needed
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "title=$TITLE" >> $GITHUB_OUTPUT
      - name: Peek title
        run: |
          echo "Title is"
          echo ${{steps.get-version.outputs.title}}
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: stable
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          title: ${{steps.get-version.outputs.title}}
          files: "*.zip"
